from sqlalchemy import Column, Integer, String, Date, Numeric
from .base import Base

class SupplierReportsAggregatedV(Base):
    __tablename__ = 'supplier_reports_aggregated_v'
    
    tenant_id = Column(Integer, primary_key=True)
    period_day = Column(Date)
    period_week = Column(Date)
    period_month = Column(Date)
    period_quarter = Column(Date)
    period_year = Column(Date)
    product_name = Column(String)
    sku = Column(String, primary_key=True)
    quantity_sold = Column(Integer)
    revenue = Column(Numeric(10, 2))
    seller_payout = Column(Numeric(10, 2))
    retail_price_max = Column(Numeric(10, 2))
    storage_fee = Column(Numeric(10, 2))
    regular_deduction = Column(Numeric(10, 2))
    dzhem_deduction = Column(Numeric(10, 2))
    delivery_rub = Column(Numeric(10, 2))
    penalty = Column(Numeric(10, 2))
    acceptance = Column(Numeric(10, 2))
    return_quantity = Column(Integer)
    return_revenue = Column(Numeric(10, 2))

class ProductMarginsMonthV(Base):
    __tablename__ = 'product_margins_month_v'
    
    tenant_id = Column(Integer, primary_key=True)
    period_month = Column(Date)
    product_name = Column(String)
    sku = Column(String, primary_key=True)
    quantity_sold = Column(Integer)
    revenue = Column(Numeric(10, 2))
    seller_payout = Column(Numeric(10, 2))
    retail_price_max = Column(Numeric(10, 2))
    tax = Column(Numeric(10, 2))
    payout_after_tax = Column(Numeric(10, 2))
    cost_per_unit = Column(Numeric(10, 2))
    total_cost = Column(Numeric(10, 2))
    storage_fee = Column(Numeric(10, 2))
    regular_deduction = Column(Numeric(10, 2))
    dzhem_deduction = Column(Numeric(10, 2))
    delivery_rub = Column(Numeric(10, 2))
    penalty = Column(Numeric(10, 2))
    acceptance = Column(Numeric(10, 2))
    return_quantity = Column(Integer)
    return_revenue = Column(Numeric(10, 2))
    margin = Column(Numeric(10, 2))
    margin_percent_revenue = Column(Numeric(10, 2))
    margin_percent_payout = Column(Numeric(10, 2))
    logistics_per_unit = Column(Numeric(10, 2))
    margin_per_unit = Column(Numeric(10, 2))